module.exports = {
  someSidebar: [
    "project-structure",
    "based-on",
    "installation",
    "add-page",
    "add-end-point",
    "getting-data-server",
    "adding-field-DB",
    "email-sending",
    "auth-middleware",
    "using-translations",
    "handling-errors",
    "form-validation",
    "socket-notifications",
    "adding-font",
    "responsiveness",
    "data-security",
    "CMS",
    "deployment",
    "add-new-component",
  ],
};
